/**
 * embed-html.js
 *
 * Le o dist/index.html do Element-Viewer e gera api/html-content.js.
 * O output inclui hash da origem e so eh escrito quando houver mudanca.
 */
import fs from "fs";
import path from "path";
import crypto from "crypto";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const HTML_INPUT = path.resolve(__dirname, "../../Element-Viewer/dist/index.html");
const JS_OUTPUT = path.resolve(__dirname, "../api/html-content.js");

console.log(`[embed-html] Lendo: ${HTML_INPUT}`);

if (!fs.existsSync(HTML_INPUT)) {
  console.error(`[embed-html] ERROR: arquivo nao encontrado: ${HTML_INPUT}`);
  console.error("[embed-html] Rode o build do Element-Viewer antes: npm run build (na pasta Element-Viewer).");
  process.exit(1);
}

const htmlRaw = fs.readFileSync(HTML_INPUT, "utf-8");
const sourceHash = crypto.createHash("sha256").update(htmlRaw).digest("hex");

console.log(`[embed-html] HTML lido: ${htmlRaw.length} caracteres`);
console.log(`[embed-html] Source SHA256: ${sourceHash}`);

const escaped = htmlRaw
  .replace(/\\/g, "\\\\")
  .replace(/`/g, "\\`")
  .replace(/\$\{/g, "\\${");

const moduleContent = `// AUTO-GENERATED - DO NOT EDIT MANUALLY
// Generated by: node scripts/embed-html.js
// Tamanho original: ${htmlRaw.length} caracteres
// Source SHA256: ${sourceHash}

export const htmlContent = \`${escaped}\`;
`;

let previous = null;
if (fs.existsSync(JS_OUTPUT)) {
  previous = fs.readFileSync(JS_OUTPUT, "utf-8");
}

if (previous === moduleContent) {
  console.log(`[embed-html] Sem alteracoes. Arquivo mantido: ${JS_OUTPUT}`);
  process.exit(0);
}

fs.writeFileSync(JS_OUTPUT, moduleContent, "utf-8");
console.log(`[embed-html] Modulo atualizado: ${JS_OUTPUT}`);
console.log(`[embed-html] Tamanho do modulo: ${moduleContent.length} caracteres`);
console.log("[embed-html] Concluido.");
